backend/Dockerfile
- Adds jupyter to system PATH so that it can be run in the CLI
=> Add Jupyter to PATH

.github/workflows/DEV-app-image-build.yaml
- **Add jupyter (and the rest of '/usr/local/bin') to PATH.**
- **Remove dependency install step in build workflow.**
=> Remove dependency install step from workflow.

.docker/compose.controller.yaml, backend/neo4j.ipynb, backend/s3_v2.py
=> Graph database testing - neo4j

backend/neo4j.ipynb
=> Update neo4j to include the Acts and Reg

.gitignore, backend/federal_law.ipynb
=> Federal law

backend/Offence_Act.ipynb, gradio/gradio-summary-retrival.py
=> summary retrival nootebook and gradio setuo

web/backend-fastapi/app/models/neo4j.py, web/backend-fastapi/app/models/topK.py, web/backend-fastapi/app/models/trulens.py
=> Add backened model folder

web/backend-fastapi/Dockerfile, web/frontend/Dockerfile
=> test deployment

.github/workflows/DEV-fastapi-image-build-push.yaml, .github/workflows/DEV-frontend-image-build-push.yaml
- **Add wildcard selectors to build & push workflows.**
- **Add wildcard selectors to build & push workflows.**
=> Add wildcard selectors to new build & push workflows.

web/frontend/src/context/Context.tsx, web/frontend/src/pages/Home/Sidebar/Sidebar.tsx
=> add context reset on logout

.docker/compose.controller.yaml, web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/config/config.ts, web/frontend/src/context/Context.tsx
=> Add pgadmin, update dependencies and fix small linting issue

web/backend-fastapi/main.py
=> Enable authorization

web/backend-fastapi/app/controllers/login.py, web/backend-fastapi/app/middleware/authentication.py, web/backend-fastapi/app/roles.json, web/backend-fastapi/entrypoint.sh, web/frontend-feedback-analytics/Dockerfile, web/frontend-feedback-analytics/feedback.html, web/frontend-feedback-analytics/login.html, web/frontend/src/config/config.ts, web/frontend/src/pages/Home/Main/Main.scss
=> keycloak Refresh token handling in backend

.docker/compose.controller.yaml, web/backend-fastapi/main.py, web/frontend/nginx.conf, web/frontend/src/config/config.ts
=> Nginx configuration update

.docker/compose.controller.yaml, web/backend-fastapi/app/models/neo4j.py
=> service reference update

.docker/compose.controller.yaml, web/backend-fastapi/app/models/neo4j.py
=> Neo4j backend

web/backend-fastapi/app/controllers/login.py, web/backend-fastapi/main.py
=> debug env variables

.docker/compose.controller.yaml, web/backend-fastapi/app/middleware/authentication.py, web/backend-fastapi/app/models/neo4j.py
=> add NEO4J_VECTOR_INDEX

web/backend-fastapi/app/models/bedrock.py
=> TEMP: Update AWS credentials handling in bedrock.py

web/backend-fastapi/main.py
=> TEMP: Update AWS credentials Print

web/backend-fastapi/main.py
=> remove the trulens dashboard and move it to a different pod

web/backend-fastapi/app/controllers/login.py, web/backend-fastapi/app/middleware/authentication.py
=> Added health check endpoint

.docker/compose.controller.yaml, web/frontend/src/assets/icons/assets.ts, web/frontend/src/assets/icons/down_arrow.svg, web/frontend/src/assets/icons/up_arrow.svg, web/frontend/src/components/FeedbackBar/FeedbackBar.scss, web/frontend/src/components/ScrollButton/ScrollButton.scss, web/frontend/src/components/ScrollButton/ScrollButton.tsx, web/frontend/src/context/Context.tsx, web/frontend/src/pages/Home/Main/Main.tsx
=> add scroll element for long text

web/backend-fastapi/Dockerfile, web/backend-fastapi/main.py
=> Use gnuicorn that is better able to handle multiple request

web/backend-fastapi/Dockerfile
=> commit code to spawn 4 workers

web/frontend/src/api/chat.ts, web/frontend/src/api/feedback.ts, web/frontend/src/context/Context.tsx, web/frontend/src/pages/Home/Sidebar/Sidebar.tsx
=> Frontend feedback

web/backend-fastapi/app/controllers/feedback.py
=> Update url forward slash

web/frontend/nginx.conf, web/frontend/src/context/Context.tsx
=> update to refresh both tokens and remove console logs

.docker/compose.controller.yaml, web/trulens-dashboard/Dockerfile, web/trulens-dashboard/main.py, web/trulens-dashboard/requirements.txt
=> Add trulens dashboard support

web/trulens-dashboard/main.py
=> bugfix: Add psycopg2 import for OperationalError in main.py

web/trulens-dashboard/.streamlit/config.toml, web/trulens-dashboard/.streamlit/credentials.toml
=> add stremlit config

web/frontend/nginx.conf, web/frontend/src/pages/Home/Main/Main.tsx
=> change timeout and add language to allow for 2 min to generate response

.docker/compose.controller.yaml, web/backend-fastapi/Dockerfile, web/frontend-feedback-analytics/default.conf
=> Update frontend and timeout

.github/workflows/ocp-airflow-scheduler-image-build-push.yaml, mlops/orchestration/airflow/Dockerfile.scheduler
- Adds `pip` installs after `USER` declaration in Dockerfile
- Updates the scheduler's base `airflow` image => 2.9.2
=> Updates airflow ver. & adds pip installs.

.github/workflows/ocp-airflow-scheduler-image-build-push.yaml, mlops/orchestration/airflow/Dockerfile.scheduler
- **Revert from is => imagestream naming**
- **Removes 'tini' entrypoint layer from Dockerfile.**
=> Change Scheduler IS & Dockerfile

.docker/compose.controller.yaml, .github/workflows/ocp-airflow-webserver-image-build-push.yaml, mlops/orchestration/airflow/Dockerfile.webserver
- **Creates airflow webserver dockerfile**
- **Adds OCP airflow webserver to compose**
- **Creates workflow for pushing OCP airflow webserver**
=> Airflow webserver Dockerfile & ImageStream

web/backend-fastapi/app/controllers/chat_RAG.py, web/backend-fastapi/app/controllers/feedback.py, web/backend-fastapi/app/models/bedrock.py, web/backend-fastapi/app/models/rag.py, web/backend-fastapi/main.py
=> Update timeout and print clean ups

HPC/HPC_Embeddings/readme.md, HPC/HPC_Embeddings/src/acts/acts.c, HPC/HPC_Embeddings/src/main.c, HPC/HPC_Embeddings/src/regulations/regulations.c, HPC/HPC_Embeddings/src/utility/xml_parser.c
=> Update HPC documentation and code

HPC/HPC_Embeddings/.bash.rc
=> add example .bashrc

web/frontend/src/pages/Home/Sidebar/Sidebar.tsx
=> remove ability to open sidebar

web/frontend/src/api/chat.ts, web/frontend/src/context/Context.tsx, web/frontend/src/pages/Home/Main/Main.tsx
=> create error dialog and add ability to refresh page on error

.docker/Dockerfile.awscron
- **Changes AWS CronJob Dockerfile.**
- **Pivot to building `oc` cli from source.**
- **Trying multi-stage build w/ verbose debug strat.**
=> change aws cron dockerfile

.docker/Dockerfile.awscron
- Installs `jq`
- Adds `AWS_DEFAULT_REGION`
=> Adds Explicit Region & `jq` to CronJob Dockerfile.

web/frontend/src/App.tsx, web/frontend/src/index.css, web/frontend/src/pages/Home/Main/Main.scss, web/frontend/src/pages/Home/Main/Main.tsx, web/frontend/src/pages/Safety/Safety.scss, web/frontend/src/pages/Safety/Safety.tsx, web/frontend/src/pages/Welcome/Welcome.scss, web/frontend/src/pages/Welcome/Welcome.tsx
=> adding ai safety, trust as a web page in the frontend

mlops/orchestration/airflow/dags/retrieve_data_dag.py
=> Update DAG script

mlops/orchestration/airflow/dags/retrieve_data_dag.py
=> add print to dag

mlops/orchestration/airflow/dags/retrieve_data_dag.py
=> add loadenv

web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/api/chat.ts, web/frontend/src/components/AnswerSection/AnswerSection.scss, web/frontend/src/components/AnswerSection/AnswerSection.tsx, web/frontend/src/components/FeedbackBar/FeedbackBar.scss, web/frontend/src/components/Modal/ModalDialog.scss, web/frontend/src/components/Modal/ModalDialog.tsx, web/frontend/src/components/ScrollButton/ScrollButton.scss, web/frontend/src/context/Context.tsx, web/frontend/src/pages/Home/Main/Main.scss, web/frontend/src/pages/Home/Main/Main.tsx, web/frontend/src/pages/Home/Sidebar/Sidebar.tsx
[ZUBA-135](https://citz-imb.atlassian.net/jira/software/c/projects/ZUBA/boards/62?selectedIssue=ZUBA-135)
=> Clean footnotes

HPC/HPC_Embeddings/include/acts_reg.h, HPC/HPC_Embeddings/include/memory_pool.h, HPC/HPC_Embeddings/src/data_structures/hash_table.c, HPC/HPC_Embeddings/src/main.c, HPC/HPC_Embeddings/src/process_acts_reg/acts_reg.c, HPC/HPC_Embeddings/src/utility/data_processing.c, HPC/HPC_Embeddings/src/utility/token_text_splitter.c
=> modularize the code and have a common act/reg function

mlops/orchestration/airflow/Dockerfile.scheduler, mlops/orchestration/airflow/dags/install_requirements.py
=> add full pat of requirements.txt

mlops/orchestration/airflow/Dockerfile.scheduler
=> manual install pip

mlops/orchestration/airflow/.docker/local/Dockerfile.scheduler, mlops/orchestration/airflow/.docker/local/Dockerfile.webserver, mlops/orchestration/airflow/.docker/ocp/Dockerfile.scheduler, mlops/orchestration/airflow/.docker/ocp/Dockerfile.webserver
=> update docker files

.docker/compose.controller.yaml, mlops/orchestration/airflow/.docker/ocp/Dockerfile.scheduler, mlops/orchestration/airflow/.docker/ocp/Dockerfile.webserver
=> adjust compose context

mlops/orchestration/airflow/dags/bclaws_scraper_dag.py
=> make a directory if one does not exist

architecture/activelearning/readme.md, readme.md
=> update and add the diagram

mlops/orchestration/airflow/.docker/ocp/Dockerfile.ocp
=> debugging steps

web/backend-fastapi/app/controllers/feedback.py
=> fix backend /submit rag fn

mlops/orchestration/airflow/dags/glossary_index_relationship_dag.py
=> Create DAG for indexing glossary and creating relationships

mlops/orchestration/airflow/dags/glossary_index_relationship_dag.py
=> Use load_dotenv

HPC/HPC_Embeddings/CMakeLists.txt, HPC/HPC_Embeddings/src/data_structures/hash_table.c, HPC/HPC_Embeddings/src/process_acts_reg/acts_reg.c, HPC/HPC_Embeddings/src/utility/token_text_splitter.c, HPC/HPC_Embeddings/src/utility/xml_parser.c
=> Fix pretokenizer bugs - punctuation and numbers

mlops/orchestration/airflow/dags/glossary_index_relationship_dag.py
=> Glossary DAG - Wait for download before opening glossary

architecture/detailedflow/readme.md, mlops/orchestration/airflow/dags/glossary_index_relationship_dag.py, readme.md
=> Update readme doc and DAG

mlops/orchestration/airflow/dags/glossary_index_relationship_dag.py
=> update dag fix

.docker/compose.controller.yaml, .gitignore, mlops/orchestration/airflow/.docker/local/Dockerfile.scheduler, mlops/orchestration/airflow/.docker/ocp/Dockerfile.scheduler, mlops/orchestration/airflow/dags/init_dbt.py, mlops/orchestration/airflow/requirements.txt, mlops/orchestration/dbt/profiles.yml, mlops/orchestration/dbt/trulens/.gitignore, mlops/orchestration/dbt/trulens/README.md, mlops/orchestration/dbt/trulens/dbt_project.yml, mlops/orchestration/dbt/trulens/models/example/my_first_dbt_model.sql, mlops/orchestration/dbt/trulens/models/example/my_second_dbt_model.sql, mlops/orchestration/dbt/trulens/models/example/schema.yml
=> Init dbt for post processing trulens data

mlops/orchestration/airflow/dags/install_dbt.py
=> dag to install dbt-postgres

web/backend-fastapi/requirements.txt, web/frontend/src/App.tsx, web/frontend/src/api/chat.ts, web/frontend/src/api/feedback.ts, web/frontend/src/components/AnswerSection/AnswerSection.scss, web/frontend/src/components/AnswerSection/AnswerSection.tsx, web/frontend/src/components/FeedbackBar/FeedbackBar.scss, web/frontend/src/components/FeedbackBar/FeedbackBar.tsx, web/frontend/src/components/Modal/ModalDialog.scss, web/frontend/src/components/Modal/ModalDialog.tsx, web/frontend/src/components/ScrollButton/ScrollButton.scss, web/frontend/src/components/ScrollButton/ScrollButton.tsx, web/frontend/src/context/Context.tsx, web/frontend/src/index.css, web/frontend/src/pages/Error/Error.scss, web/frontend/src/pages/Error/Error.tsx, web/frontend/src/pages/Home/Main/Main.scss, web/frontend/src/pages/Home/Main/Main.tsx, web/frontend/src/pages/Home/Sidebar/Sidebar.scss, web/frontend/src/pages/Home/Sidebar/Sidebar.tsx, web/frontend/src/pages/Safety/Safety.scss, web/frontend/src/pages/Safety/Safety.tsx, web/frontend/src/pages/Welcome/Welcome.scss, web/frontend/src/pages/Welcome/Welcome.tsx, web/frontend/src/utils/analytics.ts, web/frontend/src/utils/auth.ts, web/frontend/src/utils/debounce.ts
=> Frontend Analytics Sources

mlops/orchestration/airflow/dags/dbt_trulens_ETL.py
=> Update dbt DAG to use venv

mlops/orchestration/airflow/dags/dbt_trulens_ETL.py, mlops/orchestration/dbt/trulens/macros/extract_performance.sql, mlops/orchestration/dbt/trulens/macros/unroll_trulens_json_to_columns.sql, mlops/orchestration/dbt/trulens/models/example/trulens_normalize.sql
=> Unroll records_json into column

web/frontend/src/api/analytics.ts, web/frontend/src/components/AnswerSection/AnswerSection.tsx, web/frontend/src/types/types/analytics.types.ts, web/frontend/src/utils/analyticsUtil.ts
=> Analytics frontend

web/backend-fastapi/app/controllers/analytics.py, web/backend-fastapi/app/services/analytics_service.py, web/backend-fastapi/requirements.txt, web/frontend/src/api/analytics.ts, web/frontend/src/components/AnswerSection/AnswerSection.tsx, web/frontend/src/types/types/analytics.types.ts, web/frontend/src/utils/analyticsUtil.ts
=> Analytics backend

web/backend-fastapi/app/services/analytics_service.py
=> create analytics file if its not there already

web/backend-fastapi/app/models/neo4j.py, web/backend-fastapi/app/models/rag.py, web/frontend/src/components/AnswerSection/AnswerSection.tsx, web/frontend/src/components/Modal/ModalDialog.scss, web/frontend/src/types/types/chat.types.ts
=> Added references to topK

mlops/orchestration/airflow/dags/process_chunks_for_annotation.py
=> Airflow DAG to generate diffgram annotation data

mlops/orchestration/dbt/analytics/models/frontend/combined_analytics.sql, mlops/orchestration/dbt/analytics/models/frontend/schema.yml
=> create combined view for analytics

mlops/orchestration/airflow/dags/diffgram_data_preparation.py
=> add diffgram dag using files

mlops/orchestration/airflow/dags/dbt_frontend_analytics_etl.py, mlops/orchestration/airflow/dags/dbt_trulens_ETL.py, mlops/orchestration/dbt/analytics/models/frontend/combined_analytics.sql
=> Fix analytics view

mlops/orchestration/airflow/dags/dbt_frontend_analytics_etl.py
=> add longer timeout for dag

web/frontend-feedback-analytics/presentation/index.html
=> rag pipeline slide fix

readme.md, web/frontend-feedback-analytics/presentation/index.html
=> Update presentation and readme file

web/frontend-feedback-analytics/presentation/blueprint.html
=> Update blueprint slides

mlops/orchestration/airflow/dags/bclaws_image_scraper_dag.py, mlops/orchestration/airflow/dags/bclaws_txt_transform_dag.py
=> Image scraper dag

examples/diffgram_postprocessing_NER_training.ipynb, web/frontend-feedback-analytics/presentation/blueprint.html
=> Update HITL feedback infra and blueprint slides

mlops/orchestration/dbt/analytics/models/trulens/schema.yml, mlops/orchestration/dbt/analytics/models/trulens/trulens_normalize.sql
=> Update analytics to see feedback results

web/frontend-feedback-analytics/presentation/blueprint.html
=> Update annotation resource calculation

mlops/orchestration/dbt/analytics/models/trulens/trulens_simple.sql
[ZUBA-216](https://citz-imb.atlassian.net/jira/software/c/projects/ZUBA/boards/62?selectedIssue=ZUBA-216)
Adding a small view that will load quickly to help with interactive dashboards in Superset.
=> ZUBA-216 Simple Trulens Table

web/backend-fastapi/app/controllers/feedback.py, web/backend-fastapi/app/models/trulens.py
=> backend feedback changes

mlops/orchestration/dbt/analytics/models/frontend/combined_analytics.sql, mlops/orchestration/dbt/analytics/models/trulens/trulens_normalize.sql
also complete:
[ZUBA-252](https://citz-imb.atlassian.net/jira/software/c/projects/ZUBA/boards/62?selectedIssue=ZUBA-252)
=> make feedback dbt changes

HPC/HPC_Embeddings/include/mpi_def.h, HPC/HPC_Embeddings/include/token_text_splitter.h, HPC/HPC_Embeddings/include/xml_parser.h, HPC/HPC_Embeddings/mpi_receiver.py, HPC/HPC_Embeddings/requirements.txt, HPC/HPC_Embeddings/script.sh, HPC/HPC_Embeddings/src/main.c, HPC/HPC_Embeddings/src/process_acts_reg/acts_reg.c, HPC/HPC_Embeddings/src/utility/file_dram.c, HPC/HPC_Embeddings/src/utility/mpi_def.c, HPC/HPC_Embeddings/src/utility/token_text_splitter.c, HPC/HPC_Embeddings/src/utility/xml_parser.c
=> Hpc python integration

examples/Filtered Cipher Query/ai_filtered_cipher.ipynb
[ZUBA-57](https://citz-imb.atlassian.net/jira/software/c/projects/ZUBA/boards/62?selectedIssue=ZUBA-57)
- Includes a workbook that demonstrates how the user's prompt can be used to filter the nodes returned from Neo4j.
- Currently only filters based on the act_id metadata, but could be expanded if we have other metadata to act upon.
- In a Jupyter environment, run the workbook. Experiment with different questions to see how it handles the outcome.
=> ZUBA-57 AI Metadata Filtering

web/backend-fastapi/app/models/trulens.py
=> update to add explicit int values

mlops/orchestration/airflow/dags/dbt_trulens_ETL.py, mlops/orchestration/dbt/analytics/dbt_project.yml
[ZUBA-249](https://citz-imb.atlassian.net/jira/software/c/projects/ZUBA/boards/62?selectedIssue=ZUBA-249)
- change trulens views to materialized_views.
- update name of airflow dag to be more descriptive of what it's actually doing
- automatic formatting of dag
- Was able to test this and can see the materialized views created in local database. 
- Could not get a local version of superset running to check results there.
- Kept frontend analytics as tables. Probably no performance increase to change them and I've never had them run successfully on my local machine.
> - I have tested my changes to …
=> ZUBA-249 Materialized Views

readme.md
As discussed this morning:
- removed empty model folders
- fixed broken links on main README
=> Removing models & fixing links

HPC/HPC_Embeddings/include/token_text_splitter.h, HPC/HPC_Embeddings/mpi_receiver.py, HPC/HPC_Embeddings/src/process_acts_reg/acts_reg.c, HPC/HPC_Embeddings/src/utility/token_text_splitter.c
=> C tokentextspliiter

web/frontend/src/components/FeedbackBar/FeedbackBar.tsx, web/frontend/src/components/FeedbackBar/RegenerateButton/RegenerateButton.tsx, web/frontend/src/context/Context.tsx, web/frontend/src/pages/Home/Main/Main.tsx, web/frontend/src/types/types/context.types.ts
=> Regenerate answer component

examples/AtomicIndexing/index_and_insert.py, examples/AtomicIndexing/nodes.py, examples/AtomicIndexing/simple_query.py
[ZUBA-256](https://citz-imb.atlassian.net/jira/software/c/projects/ZUBA/boards/62?selectedIssue=ZUBA-256)
- Added a script to index acts and regulations down to very small components. This means that nodes in Neo4j are broken into Sections, Subsections, Paragraphs, Subparagraphs, etc.
- Added a series of node classes to help facilitate this process.
- Included a script that was used for testing the result from the database query and the response from AWS Bedrock.
- Make a backup of your database first. This process is easiest when there's a clean database.
- Run the `index_and_insert` script. It could take a while on your local. Probably close to 1.5 hours, depending on your CPU.
- Use the `simple_query` script to test the results. 
My own impressions: the similarity score doesn't feel as …
=> ZUBA-256 Indexing Nodes

examples/AtomicIndexing/README.md, examples/AtomicIndexing/detect_ref_ai.py, examples/AtomicIndexing/neo4j_functions.py, examples/AtomicIndexing/nodes.py
[ZUBA-46](https://citz-imb.atlassian.net/jira/software/c/projects/ZUBA/boards/62?selectedIssue=ZUBA-46)
- Updated the node classes so that parent nodes pass metadata to their children. Also realized that regulations can also have divisions.
- Added some functions for neo4j access. Helps get nodes, create/update edges, etc.
- `detect_ref_ai` script that uses prompt to detect references and then create relevant edges
=> ZUBA-46 Reference Edge Creation

.dvc/.gitignore, .dvcignore
=> Initialize DVC

.dvc/config, .gitignore, data.dvc
=> Init dvc cofig settings

data.dvc
=> Added dvc folder struct

data.dvc
=> neo4j backup

data.dvc
=> push full data

data.dvc
=> ZUBA-320 - Add consol42 to dvc

web/backend-fastapi/app/models/neo4j.py, web/backend-fastapi/app/models/rag.py
=> update reranker to account for images

examples/AtomicIndexing/nodes.py, mlops/orchestration/airflow/dags/atomic_nodes_create_and_join.py
[ZUBA-306](https://citz-imb.atlassian.net/jira/software/c/projects/ZUBA/boards/62?selectedIssue=ZUBA-306)
Small changes to:
- make sure the airflow dag doesn't schedule
- fix issue with tables where the version tag was getting misplaced
- fix issue with tables when there's only one row and no other headers
- fix issue with Part class if some tags weren't present
=> ZUBA-306 Follow-up

.github/workflows/dag-upload.yaml
This client helps you develop, build, deploy, and run your applications on any
OpenShift or Kubernetes cluster. It also includes the administrative
commands for managing a cluster under the 'adm' subcommand.
Basic Commands:
login             Log in to a server
new-project       Request a new project
new-app           Create a new application
status            Show an overview of the current project
project           Switch to another project
projects          Display existing projects
explain           Get documentation for a resource
Build and Deploy Commands:
rollout           Manage a Kubernetes deployment or OpenShift deployment config
rollback          Revert part of an application back to a previous deployment
new-build         Create a new build configuration
start-build …
=> Adds explicit OpenShift Client

data.dvc
=> Added iamge assets and neo4j back

web/frontend-feedback-analytics/presentation/css/layout.scss, web/frontend-feedback-analytics/presentation/index.html
=> Image presentation

documentation/preprocessing/neo4j_versions.md
[ZUBA-325](https://citz-imb.atlassian.net/jira/software/c/projects/ZUBA/boards/62?selectedIssue=ZUBA-325)
Adds a markdown file describing the differences in Neo4j over time.
=> ZUBA-325 Neo4j Versions Doc

documentation/indexing/readme.md, examples/Neo4j/datacleanup_neo4j.ipynb, readme.md
=> Update documentation readme

mlops/orchestration/airflow/dags/atomic_nodes_create_and_join.py
[ZUBA-345](https://citz-imb.atlassian.net/jira/software/c/projects/ZUBA/boards/62?selectedIssue=ZUBA-345)
Had to limit the thread count. We hit the memory limit in Airflow Scheduler using all available 20 threads.
=> ZUBA-345 Change 2

web/backend-fastapi/app/models/rag.py
=> ZUBA-321 - Append all queries for retrieval

mlops/orchestration/airflow/dags/dbt_trulens_ETL_Legacy.py, mlops/orchestration/dbt/analytics/dbt_project.yml, mlops/orchestration/dbt/analytics/models/trulens_1_4_7/schema.yml, mlops/orchestration/dbt/analytics/models/trulens_1_4_7/trulens_1_4_7_normalize.sql, mlops/orchestration/dbt/profiles.yml
=> Update DBT to use the new database

mlops/orchestration/dbt/analytics/macros/extract_dynamic_performance.sql, mlops/orchestration/dbt/analytics/models/trulens_1_4_7/schema.yml, mlops/orchestration/dbt/analytics/models/trulens_1_4_7/trulens_1_4_7_normalize.sql
=> Update dbt to show granular latency

web/backend-fastapi/app/models/rag.py
=> comment rerank

data.dvc, examples/BCLaws Scrapper/New/BCLawsScraper-Acts.py, examples/BCLaws Scrapper/New/BCLawsScraper-Regs.py
=> Remove extra whitespace

mlops/orchestration/dbt/analytics/models/trulens_1_4_7/trulens_1_4_7_normalize.sql
=> Update feedback view

mlops/orchestration/airflow/dags/analytics_full_ETL.py, mlops/orchestration/dbt/analytics/dbt_project.yml, mlops/orchestration/dbt/analytics/models/trulens_1_4_7/trulens_1_4_7_normalize.sql, mlops/orchestration/dbt/analytics/models/trulens_1_4_7_frontend_unified/schema.yml, mlops/orchestration/dbt/analytics/models/trulens_1_4_7_frontend_unified/trulens_1_4_7_frontend_unified.sql
=> Add unified data

web/frontend/src/api/chat.ts, web/frontend/src/api/feedback.ts, web/frontend/src/context/Context.tsx, web/frontend/src/pages/Home/Sidebar/Sidebar.scss, web/frontend/src/pages/Home/Sidebar/Sidebar.tsx, web/frontend/src/types/types/chat.types.ts, web/frontend/src/types/types/context.types.ts
[ZUBA-340](https://citz-imb.atlassian.net/jira/software/c/projects/ZUBA/boards/62?selectedIssue=ZUBA-340)
- Frontend calls the `/chat/states` route to get active states.
- Options menu added on left slideout. This menu allows for selection of which RAG state to use.
=> ZUBA-340 Frontend State Select

data.dvc
[ZUBA-347](https://citz-imb.atlassian.net/jira/software/c/projects/ZUBA/boards/62?selectedIssue=ZUBA-347)
As part of this ticket, pushing an updated database backup.
=> ZUBA-347 update data.dvc

HPC/HPC_Embeddings/BCLawsCopyFiles.py, HPC/HPC_Embeddings/BCLawsCopyFiles_v2.py, HPC/HPC_Embeddings/openvino/vector_openvino_one.py, HPC/HPC_Embeddings/script.sh, HPC/HPC_Embeddings/src/process_acts_reg/acts_reg.c, HPC/HPC_Embeddings/src/utility/xml_parser.c
1. Added a script to faltten the raw consolidation data to just acts and regulation
2. Updated the C code to store all the data in RAM before saving to file. No sending data to python MPI. The data is stored as JSONL
3. Added a script to test openVino performance in python.
=> HPC update to process all Consolidation

web/frontend-feedback-analytics/presentation/index.html
Based on our meeting earlier today
=> presentation updates: not on-prem wording

HPC/HPC_Embeddings/openvino_env/generate_embeddings_all.py, HPC/HPC_Embeddings/openvino_env/run_embeddings.sh, HPC/HPC_Embeddings/src/utility/token_text_splitter.c
- Added a script to process section embeddings after HPC code splits each section into 255-token chunks and saves the tokens.
- Fixed tokenization logic to correctly prepend '##' based on whether a symbol matches a known token or not.
- Added OpenVINO-based script to process all saved embeddings efficiently.
=> Add embedding post-processing script and tokenizer fix

examples/AtomicIndexing/README.md, examples/AtomicIndexing/community_generation.ipynb, examples/AtomicIndexing/community_summarization.py, examples/AtomicIndexing/index_and_insert.py
[ZUBA-276](https://citz-imb.atlassian.net/jira/software/c/projects/ZUBA/boards/62?selectedIssue=ZUBA-276)
A continuation of the community summarization ticket.
Script that includes functions to create summaries, create embeddings, insert nodes and connect them.
I'll include a file in Teams that is dropped in the atomic indexing folder if you want to test without having to generate summaries.
Uncomment the functions that you want, then run the script.
=> ZUBA-276 Community Summarization

web/backend-fastapi/app/models/rag.py, web/backend-fastapi/app/models/rag_states/v4_ImagesAndChunks.py
=> Backend changes for perplexity-images branch

web/backend-fastapi/app/models/bedrock.py, web/backend-fastapi/requirements.txt
=> Update bedrock from us to ca

data.dvc
Update the dvc hash file from committing a new neo4j backup and readme.
=> add community neo4j backup

HPC/HPC_Embeddings/include/xml_parser.h, HPC/HPC_Embeddings/src/utility/json_format.c, HPC/HPC_Embeddings/src/utility/xml_parser.c
=> Update code to add enacted date

web/backend-fastapi/app/mcp_agents/__init__.py, web/backend-fastapi/app/mcp_agents/community_detection.py, web/backend-fastapi/app/mcp_agents/semantic_search.py, web/backend-fastapi/main.py, web/backend-fastapi/requirements.txt
**1. Restart the Backend Server**
**2. Verify the MCP Server Configuration (Static Check)**
This command inspects the server's code and verifies that the tools are correctly aggregated without needing to hit the running server.
Run the following command from the `backend-fastapi` root directory within the container:
```bash
fastmcp inspect main.py:agents_mcp
```
**3. Verify the Live Endpoint (Runtime Check)**
This command sends a live request to the running server to simulate a client asking for the list of available tools (needs authorization).
Open a new terminal and run the following `curl` command:
```bash
curl -X POST \
http://localhost:10000/api/agents/mcp/ \
-H "Content-Type: application/json" \
-d '{"jsonrpc": "2.0", "method": "tools/list", "id": 1}'
```
> - I have performed a …
=> Add fastmcp to backend
